name 'phpldapadmin'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures phpldapadmin'
long_description 'Installs/Configures phpldapadmin'
version '0.1.0'
